# Generated by Django 5.2.3 on 2025-07-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_name_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('video editor', 'Video Editor'), ('script writer', 'Script Writer'), ('voice artist', 'Voice Artist')], default='script writer', max_length=50, null=True),
        ),
    ]
