# Generated by Django 5.2.3 on 2025-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
