# Generated by Django 5.2.3 on 2025-07-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_dailyreport_monthlyreport_weeklyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='file_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='file_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='file_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
