# Generated by Django 5.2.3 on 2025-07-02 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_dailyreport_file_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='month',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='week',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
