# Generated by Django 5.2.3 on 2025-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_user_alter_monthlyreport_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tag',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('script', 'Script'), ('voice', 'Voice')], max_length=100, null=True),
        ),
    ]
