# Generated by Django 5.2.3 on 2025-07-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_media_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
    ]
