# Generated by Django 5.2.3 on 2025-07-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_remove_media_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
