# Generated by Django 5.1.3 on 2025-07-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_media_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
