# Generated by Django 5.2.3 on 2025-07-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_media_approved_media_download_count'),
        ('team_managements', '0007_alter_team_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team_managements.team'),
        ),
    ]
