# Generated by Django 5.2.3 on 2025-07-04 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_managements', '0003_alter_team_manager_remove_team_users_team_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
